development:
  access_key_id: default
  secret_access_key: default

test:
  access_key_id: default
  secret_access_key: default

production:
  access_key_id: <%= ENV['S3_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
